export const users = [
  {
    id: 0,
    login: "test@mail.ru",
    password: "12345678",
    fullname: "Иванов Иван Иванович",
    role: 1,
    address: "test",
    position: "doctor",
    phone: "88005553535",
    email: "test@mail.ru",
  },
  {
    id: 1,
    login: "test@mail.ru",
    password: "12345678",
    fullname: "Иванов Иван Иванович",
    role: 1,
    address: "test",
    position: "doctor",
    phone: "88005553535",
    email: "test@mail.ru",
  },
  {
    id: 2,
    login: "test@mail.ru",
    password: "12345678",
    fullname: "Иванов Иван Иванович",
    role: 1,
    address: "test",
    position: "doctor",
    phone: "88005553535",
    email: "test@mail.ru",
  },
  {
    id: 3,
    login: "test@mail.ru",
    password: "12345678",
    fullname: "Иванов Иван Иванович",
    role: 1,
    address: "test",
    position: "doctor",
    phone: "88005553535",
    email: "test@mail.ru",
  },
];

export const patients = [
  {
    id: 0,
    fullname: "Щербатых Петр Игоревич",
    doctor: "Завадский Виталий Сергеевич",
    room: 1,
    dateStart: "2020-03-19",
    dateEnd: "2020-04-15",
    diagnoses: "Атипичная резистентная шизофрения",
    simptomes: "",
  },
];
